### ISSUE TITLE
Annotations do not render properly. Version 0.2.11

### ISSUE THREAD

**Issue by dany-cmd** [elias-sundqvist/obsidian-annotator#361] opened 2024-01-08 07:34 UTC
After the fix for the new obsidian version, the annotations do not show properly (for me 🤷 ).

Light Mode:
![grafik](https://github.com/elias-sundqvist/obsidian-annotator/assets/118031298/93e09b96-40c0-42d6-94c9-fc6831261a2d)
Dark Mode:
![grafik](https://github.com/elias-sundqvist/obsidian-annotator/assets/118031298/938b3e41-5ad5-4552-bada-2f653d5c50a2)

I hope you can find a fix for the issue. :)

**Comment by Ahmed-mo-rizk** [comment] 2024-01-08 08:02
+1

**Comment by LorenzoPolito** [comment] 2024-01-08 08:07
(plugin: v0.2.11   --  obsidian: v1.5.3) I'm also having the same issue, when there are displaing of scalidrow drowing it also give me this error: 

<img width="703" alt="image" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/26008732/3cd0bba9-ca14-4ed2-96c7-b965308a9df9">

This error pause obsidian until i click ok.

**Comment by elias-sundqvist** [comment] 2024-01-08 08:59
sigh. In those screenshots it looks like the styling was still not applied successfully for you. 
Works on my machine...

**Comment by OldVincent** [comment] 2024-01-08 09:31
@elias-sundqvist   You are right. It's still a Content Security Policy issue for stylesheets.

Screenshot from the console:
<img width="730" alt="2024-01-08 172906" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/57647667/13ffad4c-74a2-4f18-b248-e321f8632ed0">


By the way, can we just ask the Obesidian developer team to allow 'blob' type stylesheets in CSP?

**Comment by elias-sundqvist** [comment] 2024-01-08 09:57
Actually, with my fix those error messages still appear unfortunately . The style links that don't load are still expected to be there by hypothes.is, so I can't remove them, but I'm also applying the styling in another way. 
This is what it looks like on my machine. As you can see, the error messages show up, but the annotation sidebar still looks ok. 
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/9102856/07a88bca-eb8f-4217-9c86-ea59f4a668fb)
Are you also using Windows and Obsidian 1.5.3?

It sounded like the blob stylesheet CSP restriction was added for security reasons and I doubt they want to remove it. I'll try to iterate on the workaround until it works as well as before, even with the CSP restriction.

**Comment by elias-sundqvist** [comment] 2024-01-08 10:08
Actually, I was able to reproduce your by reinstalling from the community plugins list now 🤔 It worked when I did a fresh install on my phone yesterday, so I assumed it would work on all devices. 
But this is good. Should mean that I can identify and fix the problem.

**Comment by elias-sundqvist** [comment] 2024-01-08 10:12
Could you try unziping this into your `.obsidian/plugins` folder and see if it helps?
[obsidian-annotator.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13858617/obsidian-annotator.zip)

**Comment by OldVincent** [comment] 2024-01-08 10:20
It works on my computer.

<img width="1030" alt="1" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/57647667/51aee4d1-9560-44bb-9b86-ef87834bafa9">

Screenshot of the console:
<img width="730" alt="2024-01-08 172906" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/57647667/bc5da182-7f5e-4f11-9c55-8d505f552362">

**Comment by annapolaris** [comment] 2024-01-08 10:28
<img width="949" alt="屏幕截图 2024-01-08 112621" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/94355378/847d7db1-1832-4244-96fd-3fff65461646">

Same problem. I have tried this file, but unluckily it didn't work...？

> Could you try unziping this into your `.obsidian/plugins` folder and see if it helps?你能尝试把它解压缩到你的 `.obsidian/plugins` 文件夹中，看看是否有帮助吗？ [obsidian-annotator.zip 黑曜石注释器.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13858617/obsidian-annotator.zip)

screenshot of the console:
<img width="880" alt="屏幕截图 2024-01-08 112743" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/94355378/202af800-61d5-4d9a-a9ed-cc2fb0385a02">

Wondering what could be the problem.

**Comment by elias-sundqvist** [comment] 2024-01-08 10:31
@annapolaris 
And to confirm, you restarted obsidian after unzipping the file?

**Comment by annapolaris** [comment] 2024-01-08 10:31
> @annapolaris And to confirm, you restarted obsidian after unzipping the file?为了确认，您在解压缩文件后重新启动了黑曜石？

Yes

**Comment by LorenzoPolito** [comment] 2024-01-08 10:39
> Could you try unziping this into your `.obsidian/plugins` folder and see if it helps? [obsidian-annotator.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13858617/obsidian-annotator.zip)

(plugin: v0.2.11.? -- obsidian: v1.5.3 --- SO: windows)

Trying this fix for me worked on the render issue, but the error still persist.

<img width="907" alt="image" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/26008732/9cddd6e5-8e12-4c32-ba48-158bddfcfcf4">

**Comment by dany-cmd** [comment] 2024-01-08 10:47
> @annapolaris And to confirm, you restarted obsidian after unzipping the file?

Worked for me without error. Thank you!

**Comment by elias-sundqvist** [comment] 2024-01-08 10:52
@annapolaris 
I'm hoping you just did something incorrectly when installing it. 
I have re-deployed 0.2.11 with the fixed version. 
Can you try re-installing it from the community plugins tab?

**Comment by annapolaris** [comment] 2024-01-08 10:54
@elias-sundqvist 
Ok, I'll try re-instal it and see the result.

**Comment by annapolaris** [comment] 2024-01-08 11:21
> @annapolaris I'm hoping you just did something incorrectly when installing it.我希望您在安装它时做错了什么。 I have re-deployed 0.2.11 with the fixed version.我已经使用固定版本重新部署了 0.2.11。 Can you try re-installing it from the community plugins tab?您可以尝试从社区插件选项卡重新安装它吗？

Problem solved! Thank you very much!
<img width="915" alt="屏幕截图 2024-01-08 122131" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/94355378/6991e624-36f1-4eb5-94a3-d142ace2d438">

**Comment by elias-sundqvist** [comment] 2024-01-08 11:30
Great. I'll close this issue then. The JavaScript error popup seems annoying, but we can open a separate issue for that.

**Closed by elias-sundqvist** 2024-01-08 11:30 UTC
