### ISSUE TITLE
Can not find the annotation option in the more option(3 vertical dots)

### ISSUE THREAD

**Issue by tom-00** [elias-sundqvist/obsidian-annotator#63] opened 2021-09-12 15:46 UTC
So, I did exactly as the doc says;  annotation-target:: pdf location in the vault (or annotation-target-pdf:: pdf location in the vault) still cant find any annotation option.

**Comment by elias-sundqvist** [comment] 2021-09-12 15:50
duplicate of #42?

**Comment by tom-00** [comment] 2021-09-12 18:38
Thanks

**Comment by tom-00** [comment] 2021-09-12 19:01
Got the annotate option but showing a missing pdf file. I have tried with several pdf files (stored in the vault) . But still showing missing pdf file.

**Comment by tom-00** [comment] 2021-09-12 19:02
Error message: 

PDF.js v2.3.160 (build: b2856b16)
Message: Missing PDF "https://via.hypothes.is/proxy/static/xP1ZVAo-CVhW7kwNneW_oQ/1628964000/vault://home/zois/Dropbox/Research%20/paper/2019.pdf".

**Comment by elias-sundqvist** [comment] 2021-09-12 20:09
No, everything should work offline. Maybe you could send a screenshot or something to illustrate the problem?

**Comment by tom-00** [comment] 2021-09-13 03:11
![annotation ](https://user-images.githubusercontent.com/90553626/133018363-1f846990-16ce-4e2e-9425-d05d46cbf93f.png)

**Comment by tom-00** [comment] 2021-09-13 03:12
It is happening for every single pdf

**Comment by tom-00** [comment] 2021-09-13 08:03
Thanks bro, its working... and Tnx for the plugins... This single plugin can change the fate of many pdf readers. Best wishes.

**Comment by elias-sundqvist** [comment] 2021-09-13 08:56
Thanks :)

**Closed by elias-sundqvist** 2021-09-13 08:57 UTC
