### ISSUE TITLE
basic drag and drop affected

### ISSUE THREAD

**Issue by steveeyre** [elias-sundqvist/obsidian-annotator#55] opened 2021-09-09 08:37 UTC
Hi, thank you for this excellent plugin. I found a bug that after the drag and drop feature was updated, the basic drag and drop in Obsidian does not work any more. 
I disabled my plugins one-by-one to check the problem source, so I am sure it's Annotator.
Hope it can be fixed soon since I am really addicted to this plugin.

**Comment by elias-sundqvist** [comment] 2021-09-09 08:54
Duplicate of #50 
Should be fixed in the next release :)

**Closed** 2021-09-09 08:54 UTC
