### ISSUE TITLE
Why does the annotation-json show a URI / reference to a random arxiv.org PDF?

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#14] opened 2021-08-30 04:39 UTC
It seems that in the annotation JSON when I make a highlight on a local PDF that is in my vault it shows a URI / href and source to this arxiv.org PDF? https://arxiv.org/pdf/1702.08734.pdf

![image](https://user-images.githubusercontent.com/64155612/131285912-81d1dde6-1a5c-469c-a03d-deaf3a35c9a5.png)

**Comment by elias-sundqvist** [comment] 2021-08-30 05:21
Duplicate of #7

**Closed** 2021-08-30 05:21 UTC

**Comment by GitMurf** [comment] 2021-08-30 05:40
Ahhh sorry I didn't see that one.
