### ISSUE TITLE
Community plugin has the version as 0.1.9

### ISSUE THREAD

**Issue by ayyubshaffy7** [elias-sundqvist/obsidian-annotator#156] opened 2022-03-16 08:46 UTC
![image](https://user-images.githubusercontent.com/44515527/158550835-fbce6c53-465f-4541-95e4-295f7e28246c.png)

I'm not sure if it hasn't been updated or they simply forgot to change the version number

**Comment by elias-sundqvist** [comment] 2022-03-16 09:05
Duplicate of #148

**Closed** 2022-03-16 09:05 UTC
