### ISSUE TITLE
Some PDF documents can not display the text

### ISSUE THREAD

**Issue by MILKMILKKING** [elias-sundqvist/obsidian-annotator#53] opened 2021-09-08 07:55 UTC
Individual PDF documents cannot display text

I found that individual PDF documents do not display text, the document is in Traditional Chinese, is a company's prospectus, but other prospectuses in Traditional Chinese PDF can be displayed normally. I can not rule out the document is the problem, or the plug-in bug.

The left side of the picture is a plug-in to display the PDF, the right side is the normal display of PDF documents. Other pages are unable to display the text, so only show one of the pages as an example.

![image](https://user-images.githubusercontent.com/69726213/132469093-78bdcf08-0f52-4aea-98af-4c9d3a34d546.png)

**Comment by elias-sundqvist** [comment] 2021-09-08 17:36
This is probably an issue with PdfJS. 
Does the PDF display correctly in Obsidian's built-in PDF reader?

**Comment by MILKMILKKING** [comment] 2021-09-09 08:38
Hi, this document can be displayed normally in the PDF viewer that comes with obsidian.

**Comment by elias-sundqvist** [comment] 2021-09-09 08:52
Ok. Then there is some hope that this is fixable :)  Obsidian will expose its pdf.js instance in the api in the future. I will try to replace the pdf.js version in the plugin with the obsidian one then. That will hopefully make everything that works in the obsidian reader also work in the plugin.

**Comment by DarrenMMcDonald** [comment] 2021-11-01 12:56
Hello @elias-sundqvist and @MILKMILKKING. I am having the same issue with Japanese text-based PDFs. When using Annotator's PDF viewer, the Japanese text is not displayed (only the English characters intermixed in the Japanese text). However, when using the Obsidian PDF viewer, the Japanese text is displayed properly. I hope that you are able to provide a fix for this soon.

**Comment by elias-sundqvist** [comment] 2021-11-01 14:27
I'm not as busy with my studies this week, so I should be able investigate this soon. 

Do you have an example pdf that I could use for reproducing the issue?

**Comment by MILKMILKKING** [comment] 2021-11-01 14:55
> I'm not as busy with my studies this week, so I should be able investigate this soon.
> 
> Do you have an example pdf that I could use for reproducing the issue?

I can send you a PDF document with questions. What is your email address?

**Comment by elias-sundqvist** [comment] 2021-11-01 15:27
> I can send you a PDF document with questions. What is your email address?

Thanks, you can send it to github.elias@sqvist.com

**Comment by DarrenMMcDonald** [comment] 2021-11-02 00:36
@elias-sundqvist I will send you a PDF with Japanese text as well. Cheers! :)

**Comment by impermanD** [comment] 2021-11-08 09:34
This problem also appears in Chinese PDFs, especially PDF files generated by CNKI (China national knowledge infrastructure).

**Comment by impermanD** [comment] 2021-11-08 09:47
Someone also extracted this question on the PDF.js website, which is the version around 2016. https://github.com/mozilla/pdf.js/issues/7145

**Comment by Odyssian** [comment] 2021-11-22 03:20
I have a similar problem. One of the pdfs I need to annotate loads fine in the Obsidian viewer but only loads the first two pages in this plug-in. All other pages have processing wheel and don't load.

**Comment by DarrenMMcDonald** [comment] 2021-11-25 06:23
@elias-sundqvist I found one PDF in Japanese that obsidian-annotator is able to display Japanese text. Unfortunately, this only works on this one PDF. I am attaching this PDF as it may give you a hint to problem shoot this issue for the PDFs that do not work.
[簗瀬洋一郎 (2017) 組織社会化と居場所の概念整理.pdf](https://github.com/elias-sundqvist/obsidian-annotator/files/7600658/2017.pdf)

**Comment by elias-sundqvist** [comment] 2022-01-10 16:31
Status update:

I'm close to fixing this now 
![image](https://user-images.githubusercontent.com/9102856/148801462-d9b7eefb-8c8f-4622-99af-87c68d42276f.png)

I have broken some things in the process that I need to fix first, but then I should be able to share this fix in a beta release.

**Comment by DarrenMMcDonald** [comment] 2022-01-13 00:04
Could you provide the GitHub link to test the beta version of obsidian-annotator with BRAT? Thanks. :)

> 2. Get the link to the GitHub repository you want to test. The plugin developer can provide you with this link.
> It will look something like: GitMurf/my-plugin or https://github.com/GitMurf/my-plugin

**Comment by DarrenMMcDonald** [comment] 2022-01-13 06:46
I get the following error on the page that I am using obsidian-annotator on. The Japanese in the error: ブルド=build and メッセージ=message.

>PDF.js v2.11.249 (ビルド: 95435ed66)
メッセージ: Failed to fetch

I have followed all the instructions to install the test build 0.1.6 obsidian-annotator with BRAT. I am not a programmer, so I may be doing something wrong.

**Comment by linuxcjh** [comment] 2022-01-14 03:47
> I get the following error on the page that I am using obsidian-annotator on. The Simple Chinese PDF .
> 
>>  An error occurred while loading the PDF.
> > PDF.js v2.11.249 (build: 95435ed66)
> > Message: Failed to fetch
> 
> I have followed all the instructions to install the test build 0.1.6 obsidian-annotator with BRAT. 
<img width="904" alt="333" src="https://user-images.githubusercontent.com/4084295/149447998-1ac12a8f-aa97-4ea8-b614-d47f67556887.png">

**Comment by elias-sundqvist** [comment] 2022-01-14 13:11
It seems like pdf paths with Chinese characters in the name do not work at the moment. I'll try to fix that. 
If you rename the pdf to something without Chinese characters, and put it in a folder without Chinese characters, does it work for you then?

**Comment by linuxcjh** [comment] 2022-01-14 14:49
After changing the file name to English, it works fine, and the previous problem of Chinese messy code is solved. 👍🏻

**Comment by MILKMILKKING** [comment] 2022-01-14 15:00
I have been referencing PDF files outside of the obsidian document library now, may I ask if the 0.16 version of the referenced links can not bring Chinese characters?
If so, I dare not upgrade. @linuxcjh @elias-sundqvist

**Comment by elias-sundqvist** [comment] 2022-01-14 21:43
I've released a new version now (0.1.7) that should fix the problem with file names.

**Comment by linuxcjh** [comment] 2022-01-15 03:17
Good news, very efficient ; 👍🏻
I've upgraded to 0.1.7 and it's working fine, no recurrence of the previous problem.

**Comment by DarrenMMcDonald** [comment] 2022-01-16 00:41
Excellent! I can confirm also that 0.1.7 now works with PDFs with content in Japanese and also with the name of the PDF file in Japanese. Thank you so much for all your hard work in making all this possible! I think that can now make the update a public release. :)

**Comment by elias-sundqvist** [comment] 2022-01-16 16:42
> HOWEVER: I have noticed that each time I launch Obsidian [...]

Yes, I've noticed that as well. I published a new public version (0.1.8) now which should resolve that issue. 
Since the problem with Chinese text has been resolved, I will now close this issue. 
Feel free to post a new issue if you discover any other problems :)

**Closed by elias-sundqvist** 2022-01-16 16:42 UTC
Labels: bug

**Comment by MILKMILKKING** [comment] 2022-01-17 09:10
Thank you very much! I've upgraded to version 0.18 and it's great!

**Comment by DarrenMMcDonald** [comment] 2022-01-18 06:17
@elias-sundqvist I am also able to confirm that that fix works for me on the iOS version of Obsidian. The upgrade to 0.18 also fixed the issue in the iOS version where the hightlights and notes were not showing on the screen. Excellent job. Thank you so much! :)
