### ISSUE TITLE
Memory "leak" / high consumption - 1.2gb RAM when typically Obsidian sits at ~400mb

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#28] opened 2021-09-01 18:28 UTC
I can't explain exactly when/what causes this but if I open up a couple PDFs to annotate and then close them it seems like maybe the plugin is not "cleaning up" / "garbage collecting" as my RAM begins to spike and then even if I close all annotation panes and even disable the annotator plugin, it stays at this high RAM consumption until I completely close and re open Obsidian.

RAM after opening a few PDFs with annotate and then closing them. You see CPU is at virtually nothing because it isn't actually doing anything but the memory/RAM consumption is still there:

![image](https://user-images.githubusercontent.com/64155612/131724181-0b6b7488-d333-4d5a-ac4f-d99324cf423b.png)

Normal RAM of Obsidian at "steady state":

![image](https://user-images.githubusercontent.com/64155612/131724216-a140cdf9-9ff8-440b-becf-db42c2859f1f.png)

**Comment by elias-sundqvist** [comment] 2021-09-01 21:37
Hmm, that could be many things. Might take some time to localize the issue, but I agree that this should be fixed.

**Closed** 2021-09-03 13:25 UTC
Labels: bug

**Comment by elias-sundqvist** [comment] 2021-09-03 13:47
I found that the WebSocket event listeners retained references to the old annotator instances. This was hopefully the cause of the memory leak. It is fixed in the new release.

**Comment by GitMurf** [comment] 2021-09-03 17:08
Thanks! I will keep testing and let you know if I face any memory leak issues. Awesome work!
