### ISSUE TITLE
Can't annotate epub

### ISSUE THREAD

**Issue by Archie-2021** [elias-sundqvist/obsidian-annotator#68] opened 2021-09-17 08:18 UTC
I just testing this plugin and it works fine with pdf files. But when I open a epub file, there is no option for annotation and even when I add a page annotation from the side bar and it get added to the file it doesn't show up next time I open it in annotation mode. What should I do?

**Comment by elias-sundqvist** [comment] 2021-09-17 10:08
sounds like a bug... Is the highlight data saved to the markdown file? Do you get any errors in the console?

**Comment by Archie-2021** [comment] 2021-09-17 10:52
> sounds like a bug... Is the highlight/page note data saved to the markdown file? Do you get any errors in the console?
> 
> Maybe you could also send some screenshots of the issue?

Yes it saves the note it the MD file and it doesn't send any error message. It just doesn't show any options when I highlight a text

I will send a screenshot of console soon.

**Comment by Archie-2021** [comment] 2021-09-17 11:05
> sounds like a bug... Is the highlight/page note data saved to the markdown file? Do you get any errors in the console?
> 
> Maybe you could also send some screenshots of the issue?

Looks like there is a bug. Hope it is fixable. I really need this plugin to work

![Capture2021-09-17.JPG](https://user-images.githubusercontent.com/85870778/133772586-538e809f-6fd6-4d88-a29f-3a02b2a03a8a.JPG)

**Comment by elias-sundqvist** [comment] 2021-09-17 11:31
Yeah. I need to spend some more time on the epub reader, it still has some issues. I'd consider it still in alpha stage. 
The issues I'm currently aware of is
* The annotator sometimes doesn't correctly mount to the epub viewer
* Sometimes an annotator is created inside the epub page, so you get two annotation sidebars. 
* The epub reader is blank on mobile.
* clicking on highlight links sometimes only bring you to the correct chapter and not the correct page. 

I don't yet know how to fix the issues, so I can't promise that they will be fixed in the very near term, but hopefully it won't take too long before I've fixed them.

**Comment by pastorjack** [comment] 2021-09-22 17:58
I was having similar problems with the epub reader. Restarting obsidian and reloading the annotator corrected my issues.

**Comment by raisabelatrix** [comment] 2021-09-27 12:36
I'm having this problem too. Even if I restart obsidian, I still can't annotate epubs

**Comment by Archie-2021** [comment] 2021-12-26 16:19
i tried it after a while again and unfortunately still this bug persists. I really like to switch to this plugin but it must be reliable, migrating from this format is not going to be easy

**Comment by aladmit** [comment] 2022-05-14 17:26
We made a lot of changes of epub reader in latest releases. Highlighting epub became a little more stable and I personally don't get this issue anymore 🥳

**Closed by aladmit** 2022-05-14 17:26 UTC

**Comment by Archie-2021** [comment] 2022-05-15 05:26
> We made a lot of changes of epub reader in latest releases. Highlighting epub became a little more stable and I personally don't get this issue anymore 🥳

I just test it and it is a bit better than before, but it is still buggy, doesn't show the annotation half the times. like it goes into some state that not even showing annotation buttons for adding new ones, but it is fine on some pages without problem in the same note.

**Comment by aladmit** [comment] 2022-05-15 18:15
Huh 🤔  I don't see this behavior on my books anymore. I guess behavior of epub reader or annotator depends on epub content. Could u send me a book where u get the bug to aleksandrov@hey.com? And a description how to reproduce the problem.

**Comment by Archie-2021** [comment] 2022-05-17 16:38
> Huh 🤔 I don't see this behavior on my books anymore. I guess behavior of epub reader or annotator depends on epub content. Could u send me a book where u get the bug to [aleksandrov@hey.com](mailto:aleksandrov@hey.com)? And a description how to reproduce the problem.

sorry for late reply, sure. i will test it with other books too and will report the process. I used to test with multiple books but since it is an old bug for me i thought one book would be enough to judge

**Comment by StephenJamesBell** [comment] 2023-08-11 05:37
I experience the problems as described by Archie-2021...  with a correctly set annotation target of type epub, the epub can be loaded in markdown or annotation view; however...

- when text is selected in annotation view, the buttons to create an annotation or a highlight may or may not appear (quote often not) even in the same epub, even in adjacent sentences.

- when the annotate/highlight buttons do appear, it may be possible to create an annotation; however on some occasions, a second instance of a partially obscured annotation panel will appear inside the document pane - it does not appear to be possible to interact with this panel and it usually disappears in a few seconds; however

- once the foregoing happens, most functionality becomes disabled - further annotations cannot be made, selecting 'show annotation' from the markdown file will not work, and selecting a link in a regular note that points to annotation also does nothing; 

- once the foregoing has occurred, functionality can sometimes be restored by restarting Obsidian 

- there are often many errors in the developer console;  I'm not a developer so I don't know if they are meaningful to you: but here are a few examples:

- When clicking on 'show annotation' does nothing, there is usually an error in the form: peError: Cannot read properties of undefined (reading 'focusAnnotations')

Other common errors include:

- Refused to apply style from 'https://cdn.hypothes.is/hypothesis/build/styles/highlights.css?5dd56a' because its MIME type ('application/xml') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

- GET https://cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.js?cb07b6 net::ERR_ABORTED 403

-  index.html:1 Refused to execute script from 'https://cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.js?cb07b6' because its MIME type ('application/xml') is not executable, and strict MIME type checking is enabled. 

- failed to load source map: Could not load content for app://obsidian.md/annotator.css.map: System error: net::ERR_FILE_NOT_FOUND  

- error caught (in promise) TypeError: Cannot read properties of null (reading 'HTMLLinkElement')
 
Hope it helps.   The plug-in is very useful to me and I appreciate it having been created.  If it could be made more reliable when working on epubs, that would be a boon.
